version: '3.8'

services:
  frontend:
    image: ${DOCKER_USERNAME}/deputy-pwa:latest
    container_name: deputy-frontend
    restart: always
    # Порт 80 внутри контейнера, но мы не выставляем его наружу (ports:),
    # так как Nginx на сервере будет обращаться к нему по имени "frontend"
    networks:
      - app_network

networks:
  app_network:
    external: true
