import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    container: {
        paddingHorizontal: 16,
        flex: 1,
        backgroundColor: '#f3f4f6',
    },
    loadingText: {
        marginTop: 10,
        fontSize: 16,
        color: '#6b7280',
        fontFamily: 'Inter_400Regular',
    },
    unauthorizedTitle: {
        fontSize: 20,
        fontFamily: 'PlayfairDisplay_700Bold',
        color: '#0b2340',
        marginTop: 12,
        marginBottom: 8,
    },
    unauthorizedText: {
        fontSize: 15,
        color: '#6b7280',
        textAlign: 'center',
        marginBottom: 20,
        fontFamily: 'Inter_400Regular',
        paddingHorizontal: 20,
    },
    refreshButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#0f6219',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
    },
    refreshButtonText: {
        color: '#fff',
        fontSize: 14,
        fontFamily: 'Inter_600SemiBold',
        marginLeft: 8,
    },
    logoutButton: {
        padding: 8,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 12,
        marginBottom: 16,
        padding: 16,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    cardTitle: {
        fontSize: 18,
        fontFamily: 'Inter_600SemiBold',
        color: '#0b2340',
    },
    refreshIcon: {
        padding: 4,
    },
    infoRow: {
        flexDirection: 'row',
        marginBottom: 12,
        alignItems: 'center',
    },
    infoLabel: {
        fontSize: 14,
        fontFamily: 'Inter_600SemiBold',
        color: '#6b7280',
        width: 100,
    },
    infoValue: {
        fontSize: 14,
        fontFamily: 'Inter_400Regular',
        color: '#0b2340',
        flex: 1,
    },
    rolesContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        flex: 1,
    },
    roleBadge: {
        backgroundColor: '#e5e7eb',
        borderRadius: 12,
        paddingVertical: 4,
        paddingHorizontal: 10,
        marginRight: 8,
        marginBottom: 8,
    },
    roleText: {
        fontSize: 12,
        fontFamily: 'Inter_600SemiBold',
        color: '#0b2340',
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    statCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        flex: 1,
        marginHorizontal: 4,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
    statNumber: {
        fontSize: 18,
        fontFamily: 'Inter_400Regular',
        color: '#0b2340',
        marginTop: 8,
    },
    statLabel: {
        fontSize: 12,
        fontFamily: 'Inter_400Regular',
        color: '#6b7280',
        marginTop: 4,
    },
    listItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    listItemContent: {
        flex: 1,
    },
    listItemTitle: {
        fontSize: 14,
        fontFamily: 'Inter_600SemiBold',
        color: '#0b2340',
        marginBottom: 4,
    },
    listItemDate: {
        fontSize: 12,
        fontFamily: 'Inter_400Regular',
        color: '#6b7280',
    },
    eventIndicator: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#0f6219',
        marginRight: 12,
    },
});
