import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1 },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    header: { paddingHorizontal: 20, paddingBottom: 50, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
    headerTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 255, 255, 0.2)', justifyContent: 'center', alignItems: 'center' },
    headerActions: { flexDirection: 'row' },
    iconButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 255, 255, 0.2)', justifyContent: 'center', alignItems: 'center' },
    headerContent: { flex: 1 },
    headerTitle: { fontSize: 22, fontWeight: '700', color: '#FFFFFF', marginBottom: 10 },
    statusTag: { alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 4, borderRadius: 8 },
    statusTagText: { fontSize: 12, fontWeight: '600' },
    content: { padding: 16, marginTop: -30 },
    card: { backgroundColor: '#fff', borderRadius: 20, padding: 16, marginBottom: 16, elevation: 2, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 4, shadowOffset: { width: 0, height: 2 } },
    timeRow: { flexDirection: 'row', alignItems: 'center' },
    timeContent: { flex: 1 },
    timeDividerVertical: { width: 1, height: 30, backgroundColor: '#e5e7eb', marginHorizontal: 15 },
    label: { fontSize: 11, color: '#6b7280', textTransform: 'uppercase', marginBottom: 4 },
    value: { fontSize: 14, fontWeight: '600', color: '#1e293b' },
    sectionTitle: { fontSize: 16, fontWeight: '700', color: '#1e293b', marginBottom: 12 },
    description: { fontSize: 15, color: '#4b5563', lineHeight: 22, marginBottom: 15 },
    priorityBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f1f5f9', padding: 8, borderRadius: 10, alignSelf: 'flex-start' },
    dot: { width: 8, height: 8, borderRadius: 4, marginRight: 8 },
    priorityText: { fontSize: 13, fontWeight: '500' },
    attendeeRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    avatar: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    avatarText: { fontWeight: '700', color: '#166534' },
    attendeeInfo: { flex: 1 },
    attendeeName: { fontSize: 14, fontWeight: '600', color: '#1e293b' },
    statusText: { fontSize: 12, color: '#64748b' },
    statusGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    statusButton: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#fff' },
    statusButtonText: { fontSize: 13, fontWeight: '500', color: '#64748b' }
});
