import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
    container: { flex: 1 },
    loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    header: { paddingHorizontal: 20, paddingBottom: 50, borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
    headerTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
    backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 255, 255, 0.2)', justifyContent: 'center', alignItems: 'center' },
    headerActions: { flexDirection: 'row' },
    iconButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 255, 255, 0.2)', justifyContent: 'center', alignItems: 'center' },
    headerContent: { flex: 1 },
    headerTitle: { fontSize: 22, fontWeight: '700', color: '#FFFFFF', marginBottom: 10 },
    statusTag: { alignSelf: 'flex-start', paddingHorizontal: 12, paddingVertical: 4, borderRadius: 8 },
    statusTagText: { fontSize: 12, fontWeight: '600' },
    content: { padding: 16, marginTop: -55 },
    card: { backgroundColor: '#fff', borderRadius: 20, padding: 16, marginBottom: 16, elevation: 2, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 4, shadowOffset: { width: 0, height: 2 } },
    timeRow: { flexDirection: 'row', alignItems: 'center' },
    timeContent: { flex: 1 },
    timeDividerVertical: { width: 1, height: 30, backgroundColor: '#e5e7eb', marginHorizontal: 15 },
    label: { fontSize: 11, color: '#6b7280', textTransform: 'uppercase', marginBottom: 4 },
    value: { fontSize: 14, fontWeight: '600', color: '#1e293b' },
    sectionTitle: { fontSize: 16, fontWeight: '700', color: '#1e293b', marginBottom: 12 },
    description: { fontSize: 15, color: '#4b5563', lineHeight: 22, marginBottom: 15 },
    priorityBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f1f5f9', padding: 8, borderRadius: 10, alignSelf: 'flex-start' },
    dot: { width: 8, height: 8, borderRadius: 4, marginRight: 8 },
    priorityText: { fontSize: 13, fontWeight: '500' },
    attendeeRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
    avatar: { width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center', marginRight: 12 },
    avatarText: { fontWeight: '700', color: '#166534' },
    attendeeInfo: { flex: 1 },
    attendeeName: { fontSize: 14, fontWeight: '600', color: '#1e293b' },
    statusText: { fontSize: 12, color: '#64748b' },
    statusGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    statusButton: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 12, borderWidth: 1, borderColor: '#e5e7eb', backgroundColor: '#fff' },
    statusButtonText: { fontSize: 13, fontWeight: '500', color: '#64748b' },
    cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12, borderBottomWidth: 1, borderBottomColor: '#f1f5f9', paddingBottom: 8 },
    cardTitle: { fontSize: 14, fontWeight: '700', color: '#1e293b', marginLeft: 8},
    emptyText: { fontSize: 14, color: '#94a3b8', fontStyle: 'italic', textAlign: 'center', paddingVertical: 10 },
    selectWrapper: { marginBottom: 20, position: 'relative' },
    selectTrigger: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: "#fff",
        borderWidth: 1,
        borderColor: "#e5e7eb",
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    selectValue: { fontSize: 15, color: "#1e293b", fontWeight: '600' },
    selectDropdown: {
        position: 'absolute',
        top: '105%',
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 12,
        marginTop: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    selectItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
    selectItemSelected: { backgroundColor: '#f0f7f0' },
    selectItemText: { fontSize: 15, color: '#4b5563' },
    selectItemTextSelected: { color: '#166534', fontWeight: '600' },



    // --- Стили модального окна ---
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.4)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        height: '75%',
        paddingHorizontal: 20,
        paddingTop: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1e293b',
    },
    closeModalBtn: {
        padding: 4,
        backgroundColor: '#f1f5f9',
        borderRadius: 20,
    },

    // --- Стили поиска ---
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8fafc',
        borderWidth: 1,
        borderColor: '#e2e8f0',
        borderRadius: 12,
        paddingHorizontal: 12,
        height: 48,
        marginBottom: 16,
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: '#0f172a',
    },

    // --- Стили списка пользователей ---
    userListItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f1f5f9',
    },
    emptyListText: {
        textAlign: 'center',
        color: '#94a3b8',
        fontSize: 16,
        marginTop: 40,
    },
    addButtonIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#f0fdf4',
        justifyContent: 'center',
        alignItems: 'center',
    },
    removeUserBtn: {
        padding: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    completeTaskBtn: {
        backgroundColor: '#2A6E3F',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        borderRadius: 16,
        marginTop: 10,
        marginBottom: 20,
    },
    completeTaskBtnText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    commentsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 16,
        backgroundColor: '#ffffff',
    },
    commentsHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    commentsCountBadge: {
        backgroundColor: '#f1f5f9',
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    commentsCountText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#64748b',
    },
    commentsListContent: {
        paddingHorizontal: 16,
        paddingBottom: 16,
    },
    emptyCommentsContainer: {
        paddingVertical: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyCommentsText: {
        fontSize: 14,
        color: '#94a3b8',
        textAlign: 'center',
        fontStyle: 'italic',
    },

});
