name: Deploy

on:
  push:
    branches: [ main ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  SERVER_IP: 185.56.162.117

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ env.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.frontend-pwa.yml"
          target: "/home/DeputyApp"
          strip_components: 1

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/DeputyApp
            
            # Pull frontend image
            docker compose -f docker-compose.frontend-pwa.yml pull
            
            # Run it (detached mode)
            docker compose -f docker-compose.frontend-pwa.yml up -d
            
            # Reload Nginx on server to pick up new route
            docker exec nginx-proxy nginx -s reload
