- name: Copy docker-compose to server
  uses: appleboy/scp-action@v0.1.4
  with:
    host: ${{ env.SERVER_IP }}
    username: root
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    # Добавляем твой новый конфиг через запятую
    source: "Docker/docker-compose.yml,docker-compose.frontend.yml,Docker/nginx/conf.d,Docker/static"
    target: "/home/DeputyApp/"
    strip_components: 1


- name: Deploy to server
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ env.SERVER_IP }}
    username: root
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      cd /home/DeputyApp
      
      # Подтягиваем образ фронтенда
      docker compose -f docker-compose.frontend.yml pull
      
      # Запускаем его (флаг -d — в фоновом режиме)
      docker compose -f docker-compose.frontend.yml up -d
      
      # Перезагружаем Nginx на сервере, чтобы он увидел новый маршрут
      docker exec nginx-proxy nginx -s reload
